"""Control catalog and baseline membership.

The shipped catalog (data/controls.json) is generated by scripts/build_catalog.py
from the NIST SP 800-53 Rev 5 OSCAL catalog (titles, families, withdrawn flags)
and the FedRAMP Rev 5 LOW, MODERATE and HIGH OSCAL baseline profiles in
baselines/ (membership: 156, 323 and 410 controls). Any other OSCAL profile,
for example LI-SaaS, can replace a level at runtime with `load_oscal_profile`.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from importlib import resources as pkg_resources
from pathlib import Path

from .models import ImpactLevel

_OSCAL_ID = re.compile(r"^([a-z]{2})-(\d+)(?:\.(\d+))?$")
_HUMAN_ID = re.compile(r"^([A-Za-z]{2})-(\d+)(?:\((\d+)\))?$")


def to_oscal_id(control: str) -> str:
    """'SC-7(5)' -> 'sc-7.5'; already oscal ids pass through."""
    c = control.strip()
    m = _HUMAN_ID.match(c)
    if m:
        fam, num, enh = m.groups()
        return f"{fam.lower()}-{num}" + (f".{enh}" if enh else "")
    if _OSCAL_ID.match(c.lower()):
        return c.lower()
    raise ValueError(f"unrecognized control id: {control}")


def to_human_id(control: str) -> str:
    """'sc-7.5' -> 'SC-7(5)'."""
    m = _OSCAL_ID.match(control.lower())
    if not m:
        return control
    fam, num, enh = m.groups()
    return f"{fam.upper()}-{num}" + (f"({enh})" if enh else "")


@dataclass
class Control:
    id: str  # oscal form, e.g. sc-7.5
    title: str
    family: str
    baselines: set[str] = field(default_factory=set)
    withdrawn: bool = False

    @property
    def human_id(self) -> str:
        return to_human_id(self.id)

    def in_baseline(self, level: ImpactLevel) -> bool:
        return level.value in self.baselines


@dataclass
class Catalog:
    families: dict[str, str]
    controls: dict[str, Control]
    source: str = ""

    def get(self, control: str) -> Control | None:
        return self.controls.get(to_oscal_id(control))

    def for_level(self, level: ImpactLevel) -> list[Control]:
        return [c for c in self.controls.values() if c.in_baseline(level) and not c.withdrawn]

    def family_of(self, control: str) -> str:
        c = self.get(control)
        return c.family if c else to_oscal_id(control)[:2].upper()


def load_catalog(path: str | Path | None = None) -> Catalog:
    """Load the packaged catalog, or a catalog JSON in the same shape."""
    if path is None:
        text = pkg_resources.files("fedramp_viz.data").joinpath("controls.json").read_text(encoding="utf-8")
    else:
        text = Path(path).read_text(encoding="utf-8")
    raw = json.loads(text)
    controls = {
        c["id"].lower(): Control(
            id=c["id"].lower(),
            title=c["title"],
            family=c["family"],
            baselines=set(c.get("baselines", [])),
            withdrawn=bool(c.get("withdrawn")),
        )
        for c in raw["controls"]
    }
    return Catalog(families=raw["families"], controls=controls, source=raw.get("source", ""))


def load_oscal_profile(catalog: Catalog, path: str | Path, level: ImpactLevel) -> Catalog:
    """Replace baseline membership for `level` using an OSCAL profile JSON.

    Works with the NIST profiles and with the FedRAMP Rev 5 profiles
    (FedRAMP_rev5_<LEVEL>-baseline_profile.json). Controls named by the
    profile but missing from the catalog are added with a placeholder title.
    """
    raw = json.loads(Path(path).read_text(encoding="utf-8"))
    ids: set[str] = set()
    for imp in raw["profile"].get("imports", []):
        for inc in imp.get("include-controls", []):
            ids.update(i.lower() for i in inc.get("with-ids", []))
    for c in catalog.controls.values():
        c.baselines.discard(level.value)
    for cid in ids:
        ctrl = catalog.controls.get(cid)
        if ctrl is None:
            ctrl = Control(id=cid, title=f"{to_human_id(cid)} (not in packaged catalog)", family=cid.split("-")[0].upper())
            catalog.controls[cid] = ctrl
        ctrl.baselines.add(level.value)
    catalog.source += f"; {level.value} baseline overridden from {Path(path).name}"
    return catalog
